repos:
  - repo: local
    hooks:
      - id: pre-commit
        name: make pre-commit
        entry: make pre-commit
        language: system
        pass_filenames: false
        stages: [pre-commit]
      - id: pre-push
        name: make pre-push
        entry: make pre-push
        language: system
        pass_filenames: false
        stages: [pre-push]
